-- 电子宠物（儿童习惯养成）数据库结构 - MySQL 8+

CREATE TABLE IF NOT EXISTS accounts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  display_name VARCHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_accounts_username (username)
);

CREATE TABLE IF NOT EXISTS account_sessions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  account_id BIGINT UNSIGNED NOT NULL,
  session_token VARCHAR(128) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NOT NULL,
  UNIQUE KEY uniq_account_session_token (session_token),
  CONSTRAINT fk_account_sessions_account FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pet_groups (
  pet_code VARCHAR(32) PRIMARY KEY,
  display_name VARCHAR(64) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pet_assets (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  pet_code VARCHAR(32) NOT NULL,
  level_no TINYINT NOT NULL,
  score_min INT NOT NULL,
  score_max INT NULL,
  image_path VARCHAR(255) NOT NULL,
  image_format VARCHAR(16) NOT NULL DEFAULT 'webp',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_pet_level (pet_code, level_no),
  CONSTRAINT fk_pet_assets_group FOREIGN KEY (pet_code) REFERENCES pet_groups (pet_code) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ui_assets (
  asset_key VARCHAR(64) PRIMARY KEY,
  asset_group VARCHAR(32) NOT NULL,
  display_name VARCHAR(64) NOT NULL,
  image_path VARCHAR(255) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  account_id BIGINT UNSIGNED NOT NULL,
  display_name VARCHAR(64) NOT NULL,
  pet_name VARCHAR(64) NOT NULL DEFAULT '',
  starter_pet_code VARCHAR(32) NOT NULL,
  current_pet_code VARCHAR(32) NOT NULL,
  current_pet_order INT NOT NULL DEFAULT 1,
  current_pet_score INT NOT NULL DEFAULT 0,
  mood INT NOT NULL DEFAULT 0,
  stars INT NOT NULL DEFAULT 0,
  total_completed INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_users_account FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE,
  CONSTRAINT fk_users_starter_pet FOREIGN KEY (starter_pet_code) REFERENCES pet_groups (pet_code),
  CONSTRAINT fk_users_current_pet FOREIGN KEY (current_pet_code) REFERENCES pet_groups (pet_code)
);

CREATE TABLE IF NOT EXISTS user_pet_collection (
  user_id BIGINT UNSIGNED NOT NULL,
  pet_code VARCHAR(32) NOT NULL,
  pet_order INT NOT NULL,
  best_level TINYINT NOT NULL DEFAULT 1,
  best_score INT NOT NULL DEFAULT 0,
  is_current TINYINT(1) NOT NULL DEFAULT 0,
  is_max_level TINYINT(1) NOT NULL DEFAULT 0,
  unlocked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, pet_code),
  CONSTRAINT fk_collection_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_collection_pet FOREIGN KEY (pet_code) REFERENCES pet_groups (pet_code) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS task_definitions (
  id VARCHAR(64) PRIMARY KEY,
  account_id BIGINT UNSIGNED NOT NULL,
  group_name VARCHAR(32) NOT NULL,
  title VARCHAR(20) NOT NULL,
  goal TINYINT NOT NULL DEFAULT 1,
  reward_stars INT NOT NULL DEFAULT 1,
  reward_mood INT NOT NULL DEFAULT 1,
  reward_pet_score INT NOT NULL DEFAULT 10,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_task_definitions_account FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_task_progress (
  user_id BIGINT UNSIGNED NOT NULL,
  task_id VARCHAR(64) NOT NULL,
  progress_date DATE NOT NULL,
  completed_count TINYINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, task_id),
  CONSTRAINT fk_progress_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_progress_task FOREIGN KEY (task_id) REFERENCES task_definitions (id) ON DELETE CASCADE
);
